services:
  devstral-cli:
    build:
      context: .
      dockerfile: Dockerfile
    image: "nezhar/devstral-cli:${DEVSTRAL_CONTAINER_VERSION:-0.1.3}"

  devstral-proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    image: "nezhar/devstral-proxy:${DEVSTRAL_CONTAINER_VERSION:-0.1.3}"

  devstral-datasette:
    build:
      context: .
      dockerfile: Dockerfile.datasette
    image: "nezhar/devstral-datasette:${DEVSTRAL_CONTAINER_VERSION:-0.1.3}"
